version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - shared_data:/app/data
    env_file:
      - ./backend/.env

  pathway_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_pw
    network_mode: host
    volumes:
      - shared_data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - PATHWAY_HOST=0.0.0.0
      - PATHWAY_PORT=8101

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - BACKEND_URL=http://localhost:8000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    env_file:
      - ./ui/.env.local
    depends_on:
      - backend
      - pathway_backend

volumes:
  shared_data:
    driver: local
